[package]
name = "internal"
version = "0.0.0"
edition = "2021"
authors = ["Zach Ahn <engineering@zachahn.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
rustextile = "1"
