[package]
name = "chunky_projects"
version = "0.1.0"
edition = "2021"
authors = ["Zach Ahn <engineering@zachahn.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.6.2" }
